name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 0,17 * * *"
    
permissions:
  contents: write

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "mengpeng_bj@foxmail.com"
          git config --local user.name "Rae Cao"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
